export const defaultProviders = [
  {
    name: 'Dr. Aishwarya Menon',
    category: 'Lactation Consultant',
    title: 'IBCLC Certified Lactation Consultant',
    rating: 4.9,
    reviewsCount: 234,
    priceRange: '₹1,500 - ₹2,500',
    verified: true,
    featured: true,
    online: true,
    responseTime: '~2h',
    tags: ['IBCLC Certified', 'Home Visits', '24/7 Support'],
    location: 'Mumbai, Maharashtra',
  },
  {
    name: 'Priya Sharma',
    category: 'Postpartum Doula',
    title: 'Certified Postpartum Doula',
    rating: 4.8,
    reviewsCount: 189,
    priceRange: '₹3,000 - ₹5,000',
    verified: true,
    featured: true,
    online: false,
    responseTime: '~4h',
    tags: ['12 Years Exp', 'Night Care', 'Certified'],
    location: 'Bengaluru, Karnataka',
  },
  {
    name: 'Sleep Solutions',
    category: 'Pediatric Sleep Trainer',
    title: 'Sleep Coaching & Training',
    rating: 4.7,
    reviewsCount: 156,
    priceRange: '₹2,000 - ₹4,000',
    verified: true,
    featured: false,
    online: true,
    responseTime: '~1h',
    tags: ['Video Sessions', 'Follow-ups', 'Custom Plans'],
    location: 'Online',
  },
  {
    name: 'Wellness Touch',
    category: 'Prenatal Massage Therapist',
    title: 'Prenatal & Postnatal Massage',
    rating: 4.9,
    reviewsCount: 287,
    priceRange: '₹1,800 - ₹3,000',
    verified: true,
    featured: false,
    online: false,
    responseTime: '~6h',
    tags: ['Certified', 'Home Visits', 'Spa Sessions'],
    location: 'Chennai, Tamil Nadu',
  },
  {
    name: 'Little Stars Nannies',
    category: 'Newborn Care Specialist',
    title: 'Newborn & Infant Care',
    rating: 4.6,
    reviewsCount: 142,
    priceRange: '₹2,500 - ₹4,500',
    verified: true,
    featured: false,
    online: false,
    responseTime: '~8h',
    tags: ['Background Checked', 'CPR Certified'],
    location: 'Pune, Maharashtra',
  },
  {
    name: 'Dr. Meera Kapoor',
    category: 'Pediatric Nutritionist',
    title: 'Pediatric Nutrition & Meal Plans',
    rating: 4.8,
    reviewsCount: 198,
    priceRange: '₹1,200 - ₹2,800',
    verified: true,
    featured: true,
    online: true,
    responseTime: '~3h',
    tags: ['Meal Plans', 'Weaning Support', 'Allergies'],
    location: 'Online',
  },
  {
    name: 'Mindful Moms',
    category: 'Postpartum Therapist',
    title: 'Postpartum Mental Health',
    rating: 4.9,
    reviewsCount: 164,
    priceRange: '₹2,000 - ₹3,500',
    verified: true,
    featured: true,
    online: true,
    responseTime: '~2h',
    tags: ['Anxiety', 'PPD Support', 'Group Sessions'],
    location: 'Online',
  },
  {
    name: 'Active Kids Physio',
    category: 'Pediatric Physiotherapist',
    title: 'Child Development & Physiotherapy',
    rating: 4.7,
    reviewsCount: 133,
    priceRange: '₹1,800 - ₹3,200',
    verified: true,
    featured: false,
    online: false,
    responseTime: '~5h',
    tags: ['Motor Skills', 'Development', 'Exercises'],
    location: 'Delhi, NCR',
  },
];
